/// Маппинг марки авто → лого в `assets/brands/`.
/// Источники: car-logos-dataset + avto-dev/vehicle-logotypes + Simple Icons.
/// Нет файла → инициалы в [CarBrandMark].
class CarBrands {
  CarBrands._();

  static const assetDir = 'assets/brands';
  /// Mono silhouettes (black+alpha) for unified tint in UI.
  static const monoDir = 'assets/brands_mono';

  /// slug файла → список алиасов (латиница + кириллица).
  static const Map<String, List<String>> _aliases = {
    '9ff': ['9ff'],
    'abadal': ['abadal'],
    'abarth': ['abarth', 'абарт'],
    'abbottdetroit': ['abbott detroit', 'abbott-detroit', 'abbottdetroit'],
    'abt': ['abt'],
    'ac': ['ac'],
    'acura': ['acura', 'акура'],
    'aito': ['aito', 'айто'],
    'aiways': ['aiways'],
    'aixam': ['aixam'],
    'alfa': ['alfa', 'alfa romeo', 'alfaromeo', 'альфа', 'альфа ромео', 'alfa-romeo'],
    'alpina': ['alpina', 'альпина'],
    'alpine': ['alpine', 'альпин'],
    'alta': ['alta'],
    'alvis': ['alvis'],
    'amc': ['amc'],
    'apollo': ['apollo'],
    'arash': ['arash'],
    'arcfox': ['arcfox', 'аркфокс'],
    'ariel': ['ariel'],
    'aro': ['aro'],
    'arrinera': ['arrinera'],
    'arrival': ['arrival'],
    'artega': ['artega'],
    'ascari': ['ascari'],
    'askam': ['askam'],
    'aspark': ['aspark'],
    'astonmartin': ['aston martin', 'astonmartin', 'астон мартин', 'астон', 'aston-martin'],
    'atalanta': ['atalanta'],
    'auburn': ['auburn'],
    'audi': ['audi', 'ауди'],
    'aurus': ['aurus', 'аурус'],
    'austin': ['austin'],
    'autobacs': ['autobacs'],
    'autobianchi': ['autobianchi'],
    'avatr': ['avatr', 'аватр'],
    'axon': ['axon'],
    'bac': ['bac'],
    'baic': ['baic', 'baic motor', 'баик', 'баик мотор', 'baic-motor', 'baicmotor'],
    'baojun': ['baojun', 'баоджун', 'баоцзюнь'],
    'beiben': ['beiben'],
    'belgee': ['belgee', 'белджи', 'белжи'],
    'bentley': ['bentley', 'бентли'],
    'berkeley': ['berkeley'],
    'berliet': ['berliet'],
    'bertone': ['bertone'],
    'bestune': ['bestune'],
    'bharatbenz': ['bharatbenz'],
    'bitter': ['bitter'],
    'bizzarrini': ['bizzarrini'],
    'bmw': ['bmw', 'бмв'],
    'borgward': ['borgward'],
    'bowler': ['bowler'],
    'brabus': ['brabus', 'брабус'],
    'brammo': ['brammo'],
    'brilliance': ['brilliance'],
    'bristol': ['bristol'],
    'brooke': ['brooke'],
    'bufori': ['bufori'],
    'bugatti': ['bugatti', 'бугатти', 'бугатии'],
    'buick': ['buick', 'бьюик', 'буик'],
    'byd': ['byd', 'бйд', 'бид'],
    'byton': ['byton'],
    'cadillac': ['cadillac', 'кадиллак', 'кадилак'],
    'camc': ['camc'],
    'canoo': ['canoo'],
    'caparo': ['caparo'],
    'carlsson': ['carlsson'],
    'caterham': ['caterham'],
    'changan': ['changan', 'чанган', 'чангаан'],
    'changfeng': ['changfeng'],
    'chery': ['chery', 'чери'],
    'chevrolet': ['chevrolet', 'chevy', 'шевроле'],
    'chrysler': ['chrysler', 'крайслер'],
    'cisitalia': ['cisitalia'],
    'citroen': ['citroen', 'citroën', 'ситроен'],
    'cizeta': ['cizeta'],
    'cole': ['cole'],
    'correlalicorne': ['corre la licorne', 'corre-la-licorne', 'correlalicorne'],
    'cupra': ['cupra', 'купра'],
    'dacia': ['dacia', 'дачия'],
    'daewoo': ['daewoo'],
    'daf': ['daf', 'даф'],
    'daihatsu': ['daihatsu', 'дайхатсу', 'дайхацу'],
    'daimler': ['daimler'],
    'dartz': ['dartz'],
    'datsun': ['datsun'],
    'davidbrown': ['david brown', 'david-brown', 'davidbrown'],
    'dayun': ['dayun'],
    'delage': ['delage'],
    'desoto': ['desoto'],
    'detomaso': ['de tomaso', 'de-tomaso', 'detomaso'],
    'detroitelectric': ['detroit electric', 'detroit-electric', 'detroitelectric'],
    'develsixteen': ['devel sixteen', 'devel-sixteen', 'develsixteen'],
    'diatto': ['diatto'],
    'dina': ['dina'],
    'dkw': ['dkw'],
    'dmc': ['dmc'],
    'dodge': ['dodge', 'додж'],
    'dongfeng': ['dongfeng', 'донгфенг', 'дунфэн'],
    'donkervoort': ['donkervoort'],
    'drako': ['drako'],
    'ds': ['ds', 'ds automobiles', 'дс'],
    'duesenberg': ['duesenberg'],
    'eagle': ['eagle'],
    'edag': ['edag'],
    'edsel': ['edsel'],
    'eicher': ['eicher'],
    'elemental': ['elemental'],
    'elfin': ['elfin'],
    'elva': ['elva'],
    'englon': ['englon'],
    'erf': ['erf'],
    'eterniti': ['eterniti'],
    'exeed': ['exeed', 'ексид', 'эксид'],
    'facelvega': ['facel vega', 'facel-vega', 'facelvega'],
    'faradayfuture': ['faraday future', 'faraday-future', 'faradayfuture'],
    'faw': ['faw', 'фав'],
    'ferrari': ['ferrari', 'феррари'],
    'fiat': ['fiat', 'фиат'],
    'fioravanti': ['fioravanti'],
    'fisker': ['fisker'],
    'foden': ['foden'],
    'forcemotors': ['force motors', 'force-motors', 'forcemotors'],
    'ford': ['ford', 'форд'],
    'foton': ['foton'],
    'fpv': ['fpv'],
    'franklin': ['franklin'],
    'freightliner': ['freightliner'],
    'fso': ['fso'],
    'gac': ['gac', 'gac group', 'гак', 'gac-group', 'gacgroup'],
    'gardnerdouglas': ['gardner douglas', 'gardner-douglas', 'gardnerdouglas'],
    'gaz': ['gaz', 'газ', 'gazelle', 'газель', 'sobol', 'соболь'],
    'geely': ['geely', 'джили', 'геели'],
    'genesis': ['genesis', 'генезис', 'дженезис'],
    'geo': ['geo'],
    'geometry': ['geometry'],
    'gilbern': ['gilbern'],
    'gillet': ['gillet'],
    'ginetta': ['ginetta'],
    'gm': ['gm', 'general motors', 'generalmotors', 'джиэм', 'general-motors'],
    'gmc': ['gmc', 'джиэмси'],
    'goldendragon': ['golden dragon', 'golden-dragon', 'goldendragon'],
    'gonow': ['gonow'],
    'grinnall': ['grinnall'],
    'gumpert': ['gumpert'],
    'gwm': ['gwm', 'great wall', 'greatwall', 'грейт вол', 'great-wall'],
    'hafei': ['hafei'],
    'haima': ['haima'],
    'haval': ['haval', 'хавал', 'хавейл'],
    'hawtai': ['hawtai'],
    'hennessey': ['hennessey'],
    'higer': ['higer'],
    'hillman': ['hillman'],
    'hindustanmotors': ['hindustan motors', 'hindustan-motors', 'hindustanmotors'],
    'hino': ['hino'],
    'hiphi': ['hiphi', 'хипхи'],
    'hispanosuiza': ['hispano suiza', 'hispano-suiza', 'hispanosuiza'],
    'holden': ['holden'],
    'hommell': ['hommell'],
    'honda': ['honda', 'хонда'],
    'hongqi': ['hongqi', 'хунци', 'хонци'],
    'hongyan': ['hongyan'],
    'horch': ['horch'],
    'hsv': ['hsv'],
    'hudson': ['hudson'],
    'hummer': ['hummer', 'хаммер'],
    'hupmobile': ['hupmobile'],
    'hyundai': ['hyundai', 'хендай', 'хёндай', 'хюндай', 'хундай'],
    'icbus': ['ic bus', 'ic-bus', 'icbus'],
    'ih': ['ih'],
    'ikco': ['ikco'],
    'infiniti': ['infiniti', 'инфинити'],
    'innocenti': ['innocenti'],
    'intermeccanica': ['intermeccanica'],
    'international': ['international'],
    'irizar': ['irizar'],
    'isdera': ['isdera'],
    'iso': ['iso'],
    'isuzu': ['isuzu', 'исузу'],
    'iveco': ['iveco', 'ивеко'],
    'jac': ['jac', 'джак'],
    'jacmotors': ['jac motors', 'jac-motors', 'jacmotors'],
    'jaecoo': ['jaecoo', 'джаку', 'джеку', 'jaeco'],
    'jaguar': ['jaguar', 'ягуар'],
    'jawa': ['jawa'],
    'jbamotors': ['jba motors', 'jba-motors', 'jbamotors'],
    'jeep': ['jeep', 'джип'],
    'jensen': ['jensen'],
    'jetour': ['jetour', 'джетур'],
    'jetta': ['jetta', 'джетта'],
    'jmc': ['jmc'],
    'kaiser': ['kaiser'],
    'kaiyi': ['kaiyi', 'кайи', 'каийи'],
    'kamaz': ['kamaz'],
    'karlmannking': ['karlmann king', 'karlmann-king', 'karlmannking'],
    'karma': ['karma'],
    'keating': ['keating'],
    'kenworth': ['kenworth'],
    'kia': ['kia', 'киа'],
    'kinglong': ['king long', 'king-long', 'kinglong'],
    'koenigsegg': ['koenigsegg', 'кёнигсегг', 'кенигсегг'],
    'ktm': ['ktm'],
    'lada': ['lada', 'ваз', 'лада'],
    'lagonda': ['lagonda'],
    'lamborghini': ['lamborghini', 'ламборгини', 'ламборджини'],
    'lancia': ['lancia', 'ланча'],
    'landrover': ['land rover', 'landrover', 'range rover', 'rangerover', 'ленд ровер', 'лендровер', 'рендж ровер', 'рейндж ровер', 'land-rover'],
    'landwind': ['landwind'],
    'laraki': ['laraki'],
    'leapmotor': ['leapmotor', 'leap motor', 'липмотор'],
    'levc': ['levc'],
    'lexus': ['lexus', 'лексус'],
    'leyland': ['leyland'],
    'li': ['li auto', 'lixiang', 'li xiang', 'ликсианг', 'ли авто', 'лисян', 'li', 'li-auto', 'liauto'],
    'lifan': ['lifan', 'лифан'],
    'ligier': ['ligier'],
    'lincoln': ['lincoln', 'линкольн'],
    'lister': ['lister'],
    'livan': ['livan', 'ливан'],
    'lixiang': ['lixiang'],
    'lloyd': ['lloyd'],
    'lobini': ['lobini'],
    'lordstown': ['lordstown'],
    'lotus': ['lotus', 'лотос'],
    'lucid': ['lucid', 'lucid motors', 'люсид'],
    'luxgen': ['luxgen'],
    'lynkco': ['lynk', 'lynk & co', 'lynk and co', 'линк', 'линк ко', 'lynk-and-co', 'lynkandco', 'lynkco'],
    'mack': ['mack'],
    'mahindra': ['mahindra', 'махиндра'],
    'man': ['man', 'ман'],
    'mansory': ['mansory'],
    'marcos': ['marcos'],
    'marlin': ['marlin'],
    'maserati': ['maserati', 'мазерати', 'масерати'],
    'mastretta': ['mastretta'],
    'maxus': ['maxus'],
    'maybach': ['maybach', 'майбах'],
    'maz': ['maz'],
    'mazda': ['mazda', 'мазда'],
    'mazzanti': ['mazzanti'],
    'mclaren': ['mclaren', 'mc laren', 'макларен'],
    'melkus': ['melkus'],
    'mercedes': ['mercedes', 'mercedes-benz', 'mercedesbenz', 'мерседес', 'benz', 'mercedes benz'],
    'mercury': ['mercury'],
    'merkur': ['merkur'],
    'mev': ['mev'],
    'mg': ['mg', 'morris garages', 'мж', 'мг'],
    'microcar': ['microcar'],
    'mini': ['mini', 'мини'],
    'mitsubishi': ['mitsubishi', 'митсубиси', 'мицубиси', 'мицубиши'],
    'mitsuoka': ['mitsuoka'],
    'mk': ['mk'],
    'morgan': ['morgan'],
    'morris': ['morris'],
    'moskvich': ['moskvich', 'москвич', 'moskvitch'],
    'mosler': ['mosler'],
    'navistar': ['navistar'],
    'nevs': ['nevs'],
    'nikola': ['nikola'],
    'nio': ['nio', 'нио'],
    'nissan': ['nissan', 'ниссан'],
    'noble': ['noble'],
    'oldsmobile': ['oldsmobile', 'олдсмобиль'],
    'oltcit': ['oltcit'],
    'omoda': ['omoda', 'омода'],
    'opel': ['opel', 'опель'],
    'osca': ['osca'],
    'oshan': ['oshan', 'ошан'],
    'paccar': ['paccar'],
    'packard': ['packard'],
    'pagani': ['pagani', 'пагани'],
    'panhard': ['panhard'],
    'panoz': ['panoz'],
    'pegaso': ['pegaso'],
    'perodua': ['perodua'],
    'peterbilt': ['peterbilt'],
    'peugeot': ['peugeot', 'пежо'],
    'pgo': ['pgo'],
    'piercearrow': ['pierce arrow', 'pierce-arrow', 'piercearrow'],
    'pininfarina': ['pininfarina'],
    'plymouth': ['plymouth', 'плимут'],
    'polestar': ['polestar', 'полестар'],
    'pontiac': ['pontiac', 'понтиак'],
    'porsche': ['porsche', 'порше'],
    'praga': ['praga'],
    'premier': ['premier'],
    'prodrive': ['prodrive'],
    'proton': ['proton', 'протон'],
    'qoros': ['qoros'],
    'radical': ['radical'],
    'ram': ['ram', 'рам'],
    'rambler': ['rambler'],
    'ranz': ['ranz'],
    'renault': ['renault', 'рено'],
    'renaultsamsung': ['renault samsung', 'renault-samsung', 'renaultsamsung'],
    'rezvani': ['rezvani'],
    'riley': ['riley'],
    'rimac': ['rimac'],
    'rinspeed': ['rinspeed'],
    'rivian': ['rivian', 'ривиан'],
    'roewe': ['roewe'],
    'rollsroyce': ['rolls-royce', 'rolls royce', 'rollsroyce', 'роллс', 'роллс-ройс'],
    'ronart': ['ronart'],
    'rossion': ['rossion'],
    'rover': ['rover'],
    'ruf': ['ruf'],
    'saab': ['saab', 'сааб'],
    'saic': ['saic', 'saic motor', 'саик', 'saic-motor', 'saicmotor'],
    'saipa': ['saipa'],
    'saleen': ['saleen'],
    'saturn': ['saturn', 'сатурн'],
    'scania': ['scania', 'скания'],
    'scion': ['scion'],
    'seat': ['seat', 'сеат'],
    'setra': ['setra'],
    'sev': ['sev'],
    'shacman': ['shacman'],
    'simca': ['simca'],
    'singer': ['singer'],
    'singulato': ['singulato'],
    'sinotruk': ['sinotruk'],
    'sisu': ['sisu'],
    'skoda': ['skoda', 'škoda', 'шкода'],
    'smart': ['smart', 'смарт'],
    'soueast': ['soueast'],
    'spaniagta': ['spania gta', 'spania-gta', 'spaniagta'],
    'spirra': ['spirra'],
    'spyker': ['spyker'],
    'ssangyong': ['ssangyong', 'ssang yong', 'кгм', 'kgm', 'ссангйонг', 'ссанъйонг'],
    'ssc': ['ssc'],
    'sterling': ['sterling'],
    'studebaker': ['studebaker'],
    'stutz': ['stutz'],
    'subaru': ['subaru', 'субару'],
    'suffolk': ['suffolk'],
    'suzuki': ['suzuki', 'сузуки'],
    'swm': ['swm', 'свм'],
    'talbot': ['talbot'],
    'tank': ['tank', 'танк'],
    'tata': ['tata', 'тата'],
    'tatra': ['tatra'],
    'tauro': ['tauro'],
    'techart': ['techart'],
    'tesla': ['tesla', 'тесла'],
    'toyota': ['toyota', 'тойота'],
    'tramontana': ['tramontana'],
    'trion': ['trion'],
    'triumph': ['triumph'],
    'troller': ['troller'],
    'tucker': ['tucker'],
    'tvr': ['tvr'],
    'uaz': ['uaz', 'уаз'],
    'ud': ['ud'],
    'ultima': ['ultima'],
    'vandenbrink': ['vandenbrink'],
    'vauxhall': ['vauxhall', 'воксолл'],
    'vector': ['vector'],
    'vencer': ['vencer'],
    'venturi': ['venturi'],
    'venucia': ['venucia'],
    'vinfast': ['vinfast', 'винфаст'],
    'vlf': ['vlf'],
    'volkswagen': ['volkswagen', 'vw', 'фольксваген', 'фолькс', 'фольц'],
    'volvo': ['volvo', 'вольво'],
    'voyah': ['voyah', 'воя', 'воях'],
    'wanderer': ['wanderer'],
    'wartburg': ['wartburg'],
    'weltmeister': ['weltmeister'],
    'westernstar': ['western star', 'western-star', 'westernstar'],
    'westfield': ['westfield'],
    'wey': ['wey'],
    'wiesmann': ['wiesmann'],
    'willysoverland': ['willys overland', 'willys-overland', 'willysoverland'],
    'wmotors': ['w motors', 'w-motors', 'wmotors'],
    'workhorse': ['workhorse'],
    'wuling': ['wuling'],
    'xiaomi': ['xiaomi', 'сяоми'],
    'xpeng': ['xpeng', 'xiaopeng', 'кспенг', 'сяопенг'],
    'yulon': ['yulon'],
    'yutong': ['yutong'],
    'zarooqmotors': ['zarooq motors', 'zarooq-motors', 'zarooqmotors'],
    'zastava': ['zastava'],
    'zaz': ['zaz'],
    'zeekr': ['zeekr', 'зикр', 'зеекр'],
    'zenos': ['zenos'],
    'zenvo': ['zenvo'],
    'zhongtong': ['zhongtong'],
    'zinoro': ['zinoro'],
    'zotye': ['zotye'],
  };

  /// slug → имя файла (png/svg) внутри assetDir.
  static const Map<String, String> _assetFile = {
    '9ff': '9ff.png',
    'abadal': 'abadal.png',
    'abarth': 'abarth.png',
    'abbottdetroit': 'abbott-detroit.png',
    'abt': 'abt.png',
    'ac': 'ac.png',
    'acura': 'acura.png',
    'aito': 'aito.svg',
    'aiways': 'aiways.png',
    'aixam': 'aixam.png',
    'alfa': 'alfa.png',
    'alpina': 'alpina.png',
    'alpine': 'alpine.png',
    'alta': 'alta.png',
    'alvis': 'alvis.png',
    'amc': 'amc.png',
    'apollo': 'apollo.png',
    'arash': 'arash.png',
    'arcfox': 'arcfox.png',
    'ariel': 'ariel.png',
    'aro': 'aro.png',
    'arrinera': 'arrinera.png',
    'arrival': 'arrival.png',
    'artega': 'artega.png',
    'ascari': 'ascari.png',
    'askam': 'askam.png',
    'aspark': 'aspark.png',
    'astonmartin': 'astonmartin.png',
    'atalanta': 'atalanta.png',
    'auburn': 'auburn.png',
    'audi': 'audi.svg',
    'aurus': 'aurus.png',
    'austin': 'austin.png',
    'autobacs': 'autobacs.png',
    'autobianchi': 'autobianchi.png',
    'avatr': 'avatr.png',
    'axon': 'axon.png',
    'bac': 'bac.png',
    'baic': 'baic-motor.png',
    'baojun': 'baojun.png',
    'beiben': 'beiben.png',
    'belgee': 'belgee.png',
    'bentley': 'bentley.png',
    'berkeley': 'berkeley.png',
    'berliet': 'berliet.png',
    'bertone': 'bertone.png',
    'bestune': 'bestune.png',
    'bharatbenz': 'bharatbenz.png',
    'bitter': 'bitter.png',
    'bizzarrini': 'bizzarrini.png',
    'bmw': 'bmw.svg',
    'borgward': 'borgward.png',
    'bowler': 'bowler.png',
    'brabus': 'brabus.png',
    'brammo': 'brammo.png',
    'brilliance': 'brilliance.png',
    'bristol': 'bristol.png',
    'brooke': 'brooke.png',
    'bufori': 'bufori.png',
    'bugatti': 'bugatti.png',
    'buick': 'buick.png',
    'byd': 'byd.svg',
    'byton': 'byton.png',
    'cadillac': 'cadillac.png',
    'camc': 'camc.png',
    'canoo': 'canoo.png',
    'caparo': 'caparo.png',
    'carlsson': 'carlsson.png',
    'caterham': 'caterham.png',
    'changan': 'changan.png',
    'changfeng': 'changfeng.png',
    'chery': 'chery.svg',
    'chevrolet': 'chevrolet.png',
    'chrysler': 'chrysler.svg',
    'cisitalia': 'cisitalia.png',
    'citroen': 'citroen.png',
    'cizeta': 'cizeta.png',
    'cole': 'cole.png',
    'correlalicorne': 'corre-la-licorne.png',
    'cupra': 'cupra.png',
    'dacia': 'dacia.png',
    'daewoo': 'daewoo.png',
    'daf': 'daf.svg',
    'daihatsu': 'daihatsu.svg',
    'daimler': 'daimler.png',
    'dartz': 'dartz.png',
    'datsun': 'datsun.png',
    'davidbrown': 'david-brown.png',
    'dayun': 'dayun.png',
    'delage': 'delage.png',
    'desoto': 'desoto.png',
    'detomaso': 'de-tomaso.png',
    'detroitelectric': 'detroit-electric.png',
    'develsixteen': 'devel-sixteen.png',
    'diatto': 'diatto.png',
    'dina': 'dina.png',
    'dkw': 'dkw.png',
    'dmc': 'dmc.png',
    'dodge': 'dodge.png',
    'dongfeng': 'dongfeng.svg',
    'donkervoort': 'donkervoort.png',
    'drako': 'drako.png',
    'ds': 'ds.svg',
    'duesenberg': 'duesenberg.png',
    'eagle': 'eagle.svg',
    'edag': 'edag.png',
    'edsel': 'edsel.png',
    'eicher': 'eicher.png',
    'elemental': 'elemental.png',
    'elfin': 'elfin.png',
    'elva': 'elva.png',
    'englon': 'englon.png',
    'erf': 'erf.png',
    'eterniti': 'eterniti.png',
    'exeed': 'exeed.png',
    'facelvega': 'facel-vega.png',
    'faradayfuture': 'faraday-future.png',
    'faw': 'faw.svg',
    'ferrari': 'ferrari.png',
    'fiat': 'fiat.png',
    'fioravanti': 'fioravanti.png',
    'fisker': 'fisker.png',
    'foden': 'foden.png',
    'forcemotors': 'force-motors.png',
    'ford': 'ford.png',
    'foton': 'foton.png',
    'fpv': 'fpv.png',
    'franklin': 'franklin.png',
    'freightliner': 'freightliner.png',
    'fso': 'fso.png',
    'gac': 'gac-group.png',
    'gardnerdouglas': 'gardner-douglas.png',
    'gaz': 'gaz.png',
    'geely': 'geely.svg',
    'genesis': 'genesis.png',
    'geo': 'geo.png',
    'geometry': 'geometry.png',
    'gilbern': 'gilbern.png',
    'gillet': 'gillet.png',
    'ginetta': 'ginetta.png',
    'gm': 'general-motors.svg',
    'gmc': 'gmc.png',
    'goldendragon': 'golden-dragon.png',
    'gonow': 'gonow.png',
    'grinnall': 'grinnall.png',
    'gumpert': 'gumpert.png',
    'gwm': 'great-wall.png',
    'hafei': 'hafei.png',
    'haima': 'haima.png',
    'haval': 'haval.svg',
    'hawtai': 'hawtai.png',
    'hennessey': 'hennessey.png',
    'higer': 'higer.png',
    'hillman': 'hillman.png',
    'hindustanmotors': 'hindustan-motors.png',
    'hino': 'hino.png',
    'hiphi': 'hiphi.svg',
    'hispanosuiza': 'hispano-suiza.png',
    'holden': 'holden.png',
    'hommell': 'hommell.png',
    'honda': 'honda.png',
    'hongqi': 'hongqi.png',
    'hongyan': 'hongyan.png',
    'horch': 'horch.png',
    'hsv': 'hsv.png',
    'hudson': 'hudson.png',
    'hummer': 'hummer.svg',
    'hupmobile': 'hupmobile.png',
    'hyundai': 'hyundai.png',
    'icbus': 'ic-bus.png',
    'ih': 'ih.png',
    'ikco': 'ikco.png',
    'infiniti': 'infiniti.png',
    'innocenti': 'innocenti.png',
    'intermeccanica': 'intermeccanica.png',
    'international': 'international.png',
    'irizar': 'irizar.png',
    'isdera': 'isdera.png',
    'iso': 'iso.png',
    'isuzu': 'isuzu.svg',
    'iveco': 'iveco.svg',
    'jac': 'jac.png',
    'jacmotors': 'jac-motors.png',
    'jaecoo': 'jaecoo.svg',
    'jaguar': 'jaguar.png',
    'jawa': 'jawa.png',
    'jbamotors': 'jba-motors.png',
    'jeep': 'jeep.png',
    'jensen': 'jensen.png',
    'jetour': 'jetour.svg',
    'jetta': 'jetta.png',
    'jmc': 'jmc.png',
    'kaiser': 'kaiser.png',
    'kaiyi': 'kaiyi.png',
    'kamaz': 'kamaz.png',
    'karlmannking': 'karlmann-king.png',
    'karma': 'karma.png',
    'keating': 'keating.png',
    'kenworth': 'kenworth.png',
    'kia': 'kia.png',
    'kinglong': 'king-long.png',
    'koenigsegg': 'koenigsegg.png',
    'ktm': 'ktm.svg',
    'lada': 'lada.svg',
    'lagonda': 'lagonda.png',
    'lamborghini': 'lamborghini.png',
    'lancia': 'lancia.png',
    'landrover': 'landrover.png',
    'landwind': 'landwind.png',
    'laraki': 'laraki.png',
    'leapmotor': 'leapmotor.png',
    'levc': 'levc.png',
    'lexus': 'lexus.svg',
    'leyland': 'leyland.png',
    'li': 'li-auto.svg',
    'lifan': 'lifan.png',
    'ligier': 'ligier.png',
    'lincoln': 'lincoln.svg',
    'lister': 'lister.png',
    'livan': 'livan.png',
    'lixiang': 'lixiang.png',
    'lloyd': 'lloyd.png',
    'lobini': 'lobini.png',
    'lordstown': 'lordstown.png',
    'lotus': 'lotus.svg',
    'lucid': 'lucid.svg',
    'luxgen': 'luxgen.png',
    'lynkco': 'lynk-and-co.png',
    'mack': 'mack.png',
    'mahindra': 'mahindra.svg',
    'man': 'man.svg',
    'mansory': 'mansory.png',
    'marcos': 'marcos.png',
    'marlin': 'marlin.png',
    'maserati': 'maserati.png',
    'mastretta': 'mastretta.png',
    'maxus': 'maxus.png',
    'maybach': 'maybach.png',
    'maz': 'maz.png',
    'mazda': 'mazda.svg',
    'mazzanti': 'mazzanti.png',
    'mclaren': 'mclaren.png',
    'melkus': 'melkus.png',
    'mercedes': 'mercedes.svg',
    'mercury': 'mercury.png',
    'merkur': 'merkur.png',
    'mev': 'mev.png',
    'mg': 'mg.svg',
    'microcar': 'microcar.png',
    'mini': 'mini.png',
    'mitsubishi': 'mitsubishi.png',
    'mitsuoka': 'mitsuoka.png',
    'mk': 'mk.png',
    'morgan': 'morgan.png',
    'morris': 'morris.png',
    'moskvich': 'moskvitch.png',
    'mosler': 'mosler.png',
    'navistar': 'navistar.png',
    'nevs': 'nevs.png',
    'nikola': 'nikola.png',
    'nio': 'nio.svg',
    'nissan': 'nissan.svg',
    'noble': 'noble.png',
    'oldsmobile': 'oldsmobile.png',
    'oltcit': 'oltcit.png',
    'omoda': 'omoda.png',
    'opel': 'opel.png',
    'osca': 'osca.png',
    'oshan': 'oshan.png',
    'paccar': 'paccar.png',
    'packard': 'packard.png',
    'pagani': 'pagani.png',
    'panhard': 'panhard.png',
    'panoz': 'panoz.png',
    'pegaso': 'pegaso.png',
    'perodua': 'perodua.png',
    'peterbilt': 'peterbilt.png',
    'peugeot': 'peugeot.png',
    'pgo': 'pgo.png',
    'piercearrow': 'pierce-arrow.png',
    'pininfarina': 'pininfarina.png',
    'plymouth': 'plymouth.png',
    'polestar': 'polestar.svg',
    'pontiac': 'pontiac.png',
    'porsche': 'porsche.png',
    'praga': 'praga.png',
    'premier': 'premier.png',
    'prodrive': 'prodrive.png',
    'proton': 'proton.svg',
    'qoros': 'qoros.png',
    'radical': 'radical.png',
    'ram': 'ram.png',
    'rambler': 'rambler.png',
    'ranz': 'ranz.png',
    'renault': 'renault.png',
    'renaultsamsung': 'renault-samsung.png',
    'rezvani': 'rezvani.png',
    'riley': 'riley.png',
    'rimac': 'rimac.png',
    'rinspeed': 'rinspeed.png',
    'rivian': 'rivian.svg',
    'roewe': 'roewe.png',
    'rollsroyce': 'rollsroyce.png',
    'ronart': 'ronart.png',
    'rossion': 'rossion.png',
    'rover': 'rover.png',
    'ruf': 'ruf.png',
    'saab': 'saab.png',
    'saic': 'saic-motor.png',
    'saipa': 'saipa.png',
    'saleen': 'saleen.png',
    'saturn': 'saturn.svg',
    'scania': 'scania.svg',
    'scion': 'scion.png',
    'seat': 'seat.png',
    'setra': 'setra.png',
    'sev': 'sev.png',
    'shacman': 'shacman.png',
    'simca': 'simca.png',
    'singer': 'singer.png',
    'singulato': 'singulato.png',
    'sinotruk': 'sinotruk.png',
    'sisu': 'sisu.png',
    'skoda': 'skoda.svg',
    'smart': 'smart.png',
    'soueast': 'soueast.png',
    'spaniagta': 'spania-gta.png',
    'spirra': 'spirra.png',
    'spyker': 'spyker.png',
    'ssangyong': 'ssangyong.png',
    'ssc': 'ssc.png',
    'sterling': 'sterling.png',
    'studebaker': 'studebaker.png',
    'stutz': 'stutz.png',
    'subaru': 'subaru.png',
    'suffolk': 'suffolk.png',
    'suzuki': 'suzuki.png',
    'swm': 'swm.png',
    'talbot': 'talbot.png',
    'tank': 'tank.png',
    'tata': 'tata.svg',
    'tatra': 'tatra.png',
    'tauro': 'tauro.png',
    'techart': 'techart.png',
    'tesla': 'tesla.png',
    'toyota': 'toyota.png',
    'tramontana': 'tramontana.png',
    'trion': 'trion.png',
    'triumph': 'triumph.png',
    'troller': 'troller.png',
    'tucker': 'tucker.png',
    'tvr': 'tvr.png',
    'uaz': 'uaz.png',
    'ud': 'ud.png',
    'ultima': 'ultima.png',
    'vandenbrink': 'vandenbrink.png',
    'vauxhall': 'vauxhall.svg',
    'vector': 'vector.png',
    'vencer': 'vencer.png',
    'venturi': 'venturi.png',
    'venucia': 'venucia.png',
    'vinfast': 'vinfast.png',
    'vlf': 'vlf.png',
    'volkswagen': 'volkswagen.svg',
    'volvo': 'volvo.png',
    'voyah': 'voyah.png',
    'wanderer': 'wanderer.png',
    'wartburg': 'wartburg.png',
    'weltmeister': 'weltmeister.png',
    'westernstar': 'western-star.png',
    'westfield': 'westfield.png',
    'wey': 'wey.png',
    'wiesmann': 'wiesmann.png',
    'willysoverland': 'willys-overland.png',
    'wmotors': 'w-motors.png',
    'workhorse': 'workhorse.png',
    'wuling': 'wuling.png',
    'xiaomi': 'xiaomi.svg',
    'xpeng': 'xpeng.svg',
    'yulon': 'yulon.png',
    'yutong': 'yutong.png',
    'zarooqmotors': 'zarooq-motors.png',
    'zastava': 'zastava.png',
    'zaz': 'zaz.png',
    'zeekr': 'zeekr.svg',
    'zenos': 'zenos.png',
    'zenvo': 'zenvo.png',
    'zhongtong': 'zhongtong.png',
    'zinoro': 'zinoro.png',
    'zotye': 'zotye.png',
  };

  static final Map<String, String> _aliasToSlug = () {
    final m = <String, String>{};
    for (final e in _aliases.entries) {
      for (final a in e.value) {
        m[_norm(a)] = e.key;
      }
      m[_norm(e.key)] = e.key;
    }
    return m;
  }();

  static String _norm(String s) =>
      s.toLowerCase().replaceAll('ё', 'е').replaceAll(RegExp(r'[^a-zа-я0-9]+'), '');

  /// Из «Toyota Camry» / «BMW X5» → slug `toyota` / `bmw`, иначе null.
  static String? slugFor(String? makeModel) {
    final raw = (makeModel ?? '').trim();
    if (raw.isEmpty) return null;
    final lower = raw.toLowerCase();
    final compact = _norm(raw);

    final multi = _aliasToSlug.keys.where((k) => k.length >= 6).toList()
      ..sort((a, b) => b.length.compareTo(a.length));
    for (final key in multi) {
      if (compact.startsWith(key) || compact.contains(key)) {
        return _aliasToSlug[key];
      }
    }

    final first = lower.split(RegExp(r'[\s/\-]+')).firstWhere(
          (e) => e.isNotEmpty,
          orElse: () => '',
        );
    if (first.isEmpty) return null;
    final n = _norm(first);
    if (_aliasToSlug.containsKey(n)) return _aliasToSlug[n];

    for (final e in _aliasToSlug.entries) {
      if (e.key.length >= 3 && compact.startsWith(e.key)) return e.value;
    }
    return null;
  }

  static String? assetPathFor(String? makeModel) {
    final slug = slugFor(makeModel);
    if (slug == null) return null;
    final file = _assetFile[slug];
    if (file == null) return null;
    // Цветные оригиналы из brands/ (не mono).
    return '$assetDir/$file';
  }

  /// Mono-маска (если когда-нибудь снова включим brands_mono).
  static bool isMonoAsset(String? asset) {
    if (asset == null) return false;
    return asset.startsWith('$monoDir/');
  }

  /// Человекочитаемое имя марки по slug (`landrover` → `Land Rover`).
  static String displayNameForSlug(String slug) {
    final aliases = _aliases[slug];
    if (aliases == null || aliases.isEmpty) {
      return _titleCase(slug);
    }
    // Первый латинский алиас в списке — каноническое имя (не самый длинный:
    // иначе landrover → «Range Rover» из‑за длины «range rover»).
    for (final a in aliases) {
      if (RegExp(r'[а-яА-ЯёЁ]').hasMatch(a)) continue;
      return _titleCase(a);
    }
    return _titleCase(aliases.first);
  }

  /// Все марки из каталога логотипов (для автоподстановки).
  static List<String> allDisplayNames() {
    final names = _aliases.keys.map(displayNameForSlug).toSet().toList()
      ..sort((a, b) => a.toLowerCase().compareTo(b.toLowerCase()));
    return names;
  }

  static List<String> aliasesForSlug(String slug) =>
      List<String>.from(_aliases[slug] ?? const <String>[]);

  static String _titleCase(String s) {
    final parts = s.trim().split(RegExp(r'\s+'));
    return parts
        .map((p) {
          if (p.isEmpty) return p;
          if (p.contains('-')) {
            return p.split('-').map((x) {
              if (x.isEmpty) return x;
              return x[0].toUpperCase() + x.substring(1).toLowerCase();
            }).join('-');
          }
          // BMW, GMC, MG, BYD, UAZ, GAZ, VW…
          final up = p.toUpperCase();
          if (p.length <= 3 && RegExp(r'^[a-zA-Z]+$').hasMatch(p)) return up;
          return p[0].toUpperCase() + p.substring(1).toLowerCase();
        })
        .join(' ');
  }
}
